---
- name: getHostInfo
  hosts: all
  user: root

  tasks:

  - name: Log Hostname
    shell: echo "this is a test"s

  - name: log available facts
    setup: filter="*"

  - debug: msg="Hostname {{ ansible_hostname }}"