---
- name: towerUser
  hosts: all
  user: root

  tasks:

  - name: add the tower user
    user: name=tower comment="Ansible Tower Admin User" uid=1090

  - name: Drop sudoers template
    template: src=mine/sudoers dest=/etc/sudoers 

  - name: Drop tower ssh pub key template
    file: src=mine/tower.pub dest=/home/tower/.ssh/authorized_keys mode=600