---
- name: towerUser
  hosts: all
  sudo: yes
  user: tower

  tasks:

  - name: add the tower user
    user: name=tower comment="Ansible Tower Admin User" uid=1090

  - name: Drop sudoers template
    template: src=templates/sudoers dest=/etc/sudoers 

  - name: Creates /home/tower/.ssh directory
    file: path=/home/tower/.ssh state=directory owner=tower group=tower mode=700

  - name: Drop tower ssh pub key template
    template: src=templates/tower.pub dest=/home/tower/.ssh/authorized_keys owner=tower group=tower mode=600

  - name: Drop sshd_config template
    template: src=templates/sshd_config dest=/etc/ssh/sshd_config

  - name: restart ssh service
    service: name=sshd state=restarted